### ISSUE TITLE
Replace `sirsi_course_reserves_spec` tests

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1112]
Determine if there's any value in these tests or if they're covering something missed by `folio_course_reserves_spec.rb`. Incorporate what's useful and then junk the rest.

**Comment by marlo-longley** [comment]
My read on these 2 files is that everything in the sirsi file is covered in the folio file, EXCEPT the tests for facets: `crez_desk_facet`, `crez_dept_facet`,  and the several tests for `building_facet`.

**Comment by thatbudakguy** [comment]
`crez_desk_facet` and `crez_dept_facet` don't appear to be used anywhere anymore in SW (maybe they were once used on the course reserves page?)

`building_facet` is a bit weirder...i need to do more investigation to figure out if we still need these tests and if the behavior is correct for FOLIO.

**Comment by jcoyne** [comment]
We have tests for `building_facet` using folio data in https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/spec/lib/traject/config/item_info_spec.rb#L37-L165

**Comment by thatbudakguy** [comment]
Yeah, the issue is that (like with `item_display`) we rewrite/modify it in some cases based on crez info. But I can't tell what exactly the cases are supposed to be where we need to do that, and if they still exist in FOLIO.
https://github.com/sul-dlss/searchworks_traject_indexer/blob/25192c034c0f7387b7cdc3f766d77eb6c1ef9e9e/lib/traject/config/folio_config.rb#L2588-L2607
