### ISSUE TITLE
Replace tests for `all_search` field

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#1188]
References:

folio_config:
- Questions in comments for all_search: "what's in the 9XX fields set as keep_fields for all_search coming out of FOLIO?" ([link](https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/folio_config.rb#L2677))
- to_field: [(link)](https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/folio_config.rb#L227) - keep_fields listed are 024 027 028 033 905 908 920 986 979 . Code seems as what is in sirsi_config currently. 

Related spec files:

- https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/spec/integration/all_search_spec.rb
- https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/spec/lib/traject/config/all_search_spec.rb

Additional code/spec files that refer to all_search:

- https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/sdr_config.rb#L124
- https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/spec/integration/sdr_config_spec.rb#L80

**Comment by hudajkhan** [comment]
The logic for all search fields is about the same, and the test
Quick comparison of all_search and marc_json_struct between older copy of Solr index and current. 

- id: 14156104.  The main difference in all_search was that the older version had 'UNAUTHORIZED' and strings like '^A3364769' next to the LC Genre Form terms/URIs.  This difference seems to stem from the MARC itself (fields 100 and 655), since the older marc_json_struct had these values and the newer one did not. 
- id: 14136534. Similar difference with 'UNAUTHORIZED'.  Older MARC has {"100":{"ind1":"1","ind2":" ","subfields":[{"a":"Weldin, Brian Jepson Michael Margolis Nicholas Robert."},{"?":"UNAUTHORIZED"}]}} whereas current MARC has {"100":{"ind1":"1","ind2":" ","subfields":[{"a":"Weldin, Brian Jepson Michael Margolis Nicholas Robert."}]}}.

**Comment by hudajkhan** [comment]
Everything looks fine for the time being, so we'll go ahead and close this issue.
