### ISSUE TITLE
Geo Aardvark: schema changes

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/searchworks_traject_indexer#1514]
- [x] Only georeferenced maps should have the class 'Maps.' Currently, all raster data are classified as Maps (ex. Bathymetric GeoTIFFs such as this one: https://earthworks-stage.stanford.edu/catalog/stanford-wc605vp7672)
       The mapping logic for gbl_resourceClass_sm should be the same as it is for the gbl_georeferenced_b element:
               IF title.value CONTAINS '(Raster Image)' > Resource Class = Maps

- [x]  For dc_source_sm element: Only create this element if the item has a PURL. Apologies for not catching this sooner, but there are some georeferenced maps that have been sourced from other applications (such as the David Rumsey Map Collection site) and the identifiers that are generated will be invalid, see the dc_source_sm element this example:https://earthworks-stage.stanford.edu/catalog/stanford-yx324nv8969/raw

- [x] Update dcat_theme_sm mapping (see below)

**Comment by kimdurante** [comment]
Hi Again. I cannot edit this ticket, so I'm adding this here in the comments. 
Because the Aardvark schema uses modified terms for some ISO topic category values, I would recommend the following for mapping for the `dcat_theme_sm` element:

IF subject*.source.code = ISO19115TopicCategory AND subject*.value = Climatology, Meteorology and Atmosphere > Climate

IF subject*.source.code = ISO19115TopicCategory AND subject*.value = Planning and Cadastral > Property

IF subject.type=topic AND subject.value = Aerial photographs OR Aerial surveys OR Bathymetric maps OR California as an island--Maps OR Composite map OR Landsat satellites OR Multibeam mapping OR Nautical charts OR Remote sensing OR Remote sensing images OR Satellite image maps > Imagery

IF subject.type = topic AND subject.value = Coasts OR Forests OR Forest canopies OR Forests and forestry OR Hydrology OR Hydrography OR Land cover OR Landforms OR Vegetation mapping > Land cover

OTHERWISE IF subject*.source.code=ISO19115TopicCategory > subject*.value


I hope this is not too confusing, happy to chat about it. This one is not a huge priority for me due to the fact that subjects and themes are inconsistently applied, and also that metadata for scanned maps do not include ISO topics, so a complete mapping to the dcat_theme element will require much more analysis, especially as we add more maps to EarthWorks
