### ISSUE TITLE
collection_info needs to get collection's title from MODS title data instead of identityMetadata

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/searchworks_traject_indexer#250]
The user facing problem is: collection items released to SearchWorks have an incorrect collection title displayed.

Related details here - https://github.com/sul-dlss/discovery-indexer/issues/32

**Comment by blalbrit** [comment]
As an example, see this screenshot (note, difference between collection title in the child objects vs. collection title of collection object):

![screenshot 2019-01-16 16 15 28](https://user-images.githubusercontent.com/796990/51287058-96ffec00-19aa-11e9-8b1c-572fd93fa75a.png)

**Comment by cebraj** [comment]
Adding another example. Collection title spelling was changed in MARC/Symphony and MODS/Argo, but Searchworks search results list view still displays the old title. See the spelling of "Baisheng" versus "Bosheng" (old spelling).

![wrong_collection_title_in_results_list_view](https://user-images.githubusercontent.com/36009432/69192442-6c565680-0ad9-11ea-8b5b-55408f143d5e.JPG)

**Comment by andrewjbtw** [comment]
Jessica and I looked into this further yesterday to try to determine if any steps could be taken from the SDR/Fedora/Argo side to update the collection title in the search results display.

Things that Jessica had already updated in Argo that did not have an effect on the SearchWorks display:

1. Updating the title in the DC datastream in Argo.
2. Updating the <objectLabel> in the identityMetadata datastream in Argo.

I believe this re-confirms the investigation done on previous tickets related to this issue (see link in first comment above), that found that none of the DC, identity metadata, or descriptive metadata have an effect on this part of the SearchWorks view.

The only other place I could think to change this title was in the Fedora object label itself, in the Fedora admin interface:

![Screen Shot 2019-11-26 at 1 08 10 PM](https://user-images.githubusercontent.com/8975583/69673096-68cd4d00-104e-11ea-9058-e62307de8dec.png)

This change had an immediate effect and now SearchWorks is displaying the correct collection title in the results.

Given that Fedora is going to be retired, that the graphical interface to editing Fedora now seems to be accessible only in certain browsers (Chrome is what I use for it) and requires re-enabling Flash, and given that only a very limited set of users even has access to Fedora, I would strongly suggest that SearchWorks pull the data for this field from a source that is readily accessible to and editable by those who routinely edit metadata.

**Comment by andrewjbtw** [comment]
Another example of what appears to be the same issue: 

https://searchworks.stanford.edu/catalog?utf8=%E2%9C%93&search_field=search&q=jenny+lind+collection

The collection title is:  Jenny Lind collection, 1835-1919
The collection title shown in individual results in the list is: Jenny Lind papers, 1835-1917

![Screen Shot 2020-01-08 at 9 31 14 AM](https://user-images.githubusercontent.com/8975583/72001278-f8434f80-31f9-11ea-806a-6a3696aaa321.png)

However, I should note that I've now updated the label in the Fedora object with the correct collection title, and I've gone to Argo and updated the DC title and the label in the identityMetadata, but this time the SearchWorks results have not changed to reflect the change. So it's possible that the underlying issue is not actually the Fedora object label.

Ultimately, the collection title in the search results should be coming from the MODS so that updates there update SearchWorks.

**Comment by cebraj** [comment]
Another title change had been made recently to the Wang Jingwei collection mentioned above. Within the past few days Andrew Berger updated the change in the Fedora label, and I updated the DC and identityMD datastreams in Argo, but the collection title still wasn't changing automatically in SW. But today I released the collection and the update is now reflected in SW, so I guess this collection needed to be manually re-released too...
