### ISSUE TITLE
Content notes (505) should be line breaking at --

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/searchworks_traject_indexer#387]
examples 
https://searchworks.stanford.edu/view/12845889
https://searchworks.stanford.edu/view/13312935

SW-3854
SW-3848

**Comment by jkeck** [comment]
I looked into this a little bit, and I've tracked down where this is happening.  In the line https://github.com/sul-dlss/searchworks_traject_indexer/blob/3b984db0cdde0936faaa28a7bf267c66429bdde6/lib/traject/config/sirsi_config.rb#L1921 we have a Regexp union.  The 4th regex that in that list is

```
/(?=(?<!Chapter|Section|Appendix|Part|v\.) \d+[:\.-]?\s+)/i
```

This is a negative lookbehind before the match.  I loosely parse this as any 1 or more digits surrounded by spaces that is not preceded by `Chapter`, `Section`, `Appending`, `Part`, or `v`.

This is why we're seeing a split before the ` 3 ` and the ` 7 ` in 12845889 and the ` 1982 ` in 13312935.

I'm not 100% sure what the goal of this particular line is, but removing it causes one spec to fail pretty badly https://github.com/sul-dlss/searchworks_traject_indexer/blob/3b984db0cdde0936faaa28a7bf267c66429bdde6/spec/lib/traject/config/note_fields_spec.rb#L224-L250

I can make the delimiter after the digit non-optional (e.g. change ` \d+[:\.-]?\s+` to ` \d+[:\.-]\s+`) so that this will only match on numbers that have a `:`, `.`, or `-` after it (which is what that particular test data has, but not 100% sure of the ultimate consequences and if that is still to the spirit of the original intent).

I'll submit a PR w/ that change and see what folks think
