### ISSUE TITLE
Index MHLD data from FOLIO

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#664]
Getting the MHLD data probably requires extra requests to FOLIO. Once retrieved, it should be indexed as we do with Symphony.

Mappings:
https://docs.google.com/spreadsheets/d/1_q7wz6GVpa383GxKqR-lk8SQwlgVyKAH_3ShIHgmdCc/edit#gid=0

**Comment by thatbudakguy** [comment]
blocked on https://github.com/sul-dlss/libsys-airflow/issues/133

**Comment by thatbudakguy** [comment]
- [ ] find a instance/bib whose FOLIO holdings were created from an MHLD; the journal "National Geographic" is a good example: https://folio-test.stanford.edu/inventory/view/cc3d8728-a6b9-45c4-ad0c-432873c3ae47
- [ ] look at how "National Geographic" appears in current (symphony-backed) production SearchWorks: https://searchworks.stanford.edu/view/576562
- [ ] check how it looks in searchworks-folio-dev; observe the differences/things missing from the record
- [ ] figure out what needs to change in our indexing config so that things go in the right places

see [this Miro board](https://miro.com/app/board/uXjVOeViGSY=/?moveToWidget=3458764549588453998&cot=14) for details on MHLD mappings.

**Comment by thatbudakguy** [comment]
the place to look is the "at the library" panel, specifically at the small bits of text at the top of each library

**Comment by jcoyne** [comment]
```
require 'folio_client'
client = FolioClient.new url:ENV.fetch('OKAPI_URL')
record = client.source_record(instanceHrid: 'in00000000204')
record.holdings.map { |holding| holding.dig('holdingsStatements') }
 => [[{"note"=>"Library has latest 10 yrs. only."}, {"statement"=>"v.195(1999)-v.196(1999),v.201(2002),v.203(2003)-"}], []]
```

**Comment by cbeer** [comment]
See https://github.com/sul-dlss/searchworks_traject_indexer/pull/812 etc.
