### ISSUE TITLE
Add item UUIDs to records to support RTAC queries

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#696]
dependency of https://github.com/sul-dlss/SearchWorks/issues/2964

instead of barcodes, we need item UUIDs to make RTAC requests in SearchWorks and display availability info. that means we need the item UUIDs to be indexed.

**Comment by cbeer** [comment]
Should we re-add the `holdings_json_struct` so Searchworks can pull it out of that?

**Comment by corylown** [comment]
The only other thought I had was to add a new field that would eventually replace `item_display` but store a json string with keys/values (instead of a string with delimiters) and add item_uuid to that. Maybe for now using `holdings_json_struct` to fetch the uuid from the barcode is the simplest approach.

**Comment by thatbudakguy** [comment]
closing since we're just using the existing `holdings_json_struct` (for now).
