### ISSUE TITLE
Data Control Report information

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#74]
- [ ] Unexpected date2 for type c after usable date1 in 008 for record 96: 741114c19611923gw sub        |n  | ger 
- [ ] Unexpectedly found usable date1 in 008 for record: 258: 731231|1930||||gw            ||| | ger  
- [ ] record 7390 has invalid DEWEY callnumber: 374.24 .YL743 S6
- [ ] record 15019 has invalid LC callnumber: BS1965 1963
- [ ] record 7098089 has XX callnumber but current location is not ON-ORDER or INPROCESS or shadowy
- [ ] ???

**Comment by shelleydoljack** [comment]
We decided to have these reports done outside the traject pipeline. Currently trying to replicate these using BC Analytics. Using this ticket to track progress on that.

**Comment by ahafele** [comment]
Document on current state from DC perspective. https://docs.google.com/document/d/1E6Gte32QHRJ7z-wDnQo6shYFiI0zxLjZUOqwC1oSvX8/edit

**Comment by shelleydoljack** [comment]
I created the following reports in BC Analytics:

- Multiple 1XX fields
- Multiple 240 fields
- Multiple 245 fields
- Multiple 008 fields
- 880 fields with multiple $61XX
- 880 fields with multiple $6240
- 880 fields with multiple $6245
- Items with XX call numbers and current location not INPROCESS, ON-ORDER, SPEC-INPRO, or shadowed

They represent what we currently report on with solrmarc-sw, except for reporting invalid LC or Dewey callnums. For all of these reports, I set them up so that we only report on SUL records, records not shadowed, and records with catalog date modified in past 7 days. It’s quite easy to adjust these parameters once we get feedback from Data Control about them.
