### ISSUE TITLE
Index eResources data from FOLIO

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#767]

**Comment by thatbudakguy** [comment]
There was some discussion around using a FOLIO-specific "electronic access" field for these resources, but since our last workcycle we've determined that we're going to just keep them the way they are, so eResources are just regular MARC with a link in the 856 field.

Thus, we think nothing special needs to be done to index them — just need to confirm this by looking at some example items and then this ticket can be closed.

**Comment by thatbudakguy** [comment]
@ahafele can maybe get us some examples?

**Comment by ahafele** [comment]
https://folio-test.stanford.edu/inventory/view/342bbef8-494c-5726-abe9-50df6fe50b43  - a12451243
https://folio-test.stanford.edu/inventory/view/50419099-0b7c-54aa-bd73-31bf14a7fb4a   - a13288549
https://folio-test.stanford.edu/inventory/view/73f4837b-fe9a-5f3c-aadc-740e86b9f49e    - a10151431 (purl example)

**Comment by thatbudakguy** [comment]
sw-folio-dev may not have the records at all: indexing is being skipped? need to figure out why. see e.g. https://searchworks-folio-dev.stanford.edu/view/12451243

**Comment by corylown** [comment]
Both [a10151431](https://searchworks-folio-dev.stanford.edu/view/10151431) and [a13288549](https://searchworks-folio-dev.stanford.edu/view/13288549) are handled correctly, with links/embed showing up in the right place. Looking into why [a12451243](https://searchworks-folio-dev.stanford.edu/view/12451243) isn't indexed at all.

**Comment by corylown** [comment]
We think we want to construct `item_display` and related fields for records that are electronic records with an 856 link that do not have an item in FOLIO.

**Comment by corylown** [comment]
@ahafele @saseestone currently, in SearchWorks you can apply filters to get to e-resources that are provided by Lane (or other libraries): https://searchworks.stanford.edu/?f%5Baccess_facet%5D%5B%5D=Online&f%5Bbuilding_facet%5D%5B%5D=Medical+%28Lane%29.

- Do we want to continue to provide this feature?
- If so, what in the record will indicate the library for the record because typically this comes from the item/holdings info that e-resources in FOLIO do not have.
- Some examples of e-resource records in folio-test that are from Lane and Law would also be helpful.

Thank you!

**Comment by cbeer** [comment]
> If so, what in the record will indicate the library for the record

I think the holdings have a permanent/effective location that should give the library, at least.

**Comment by ahafele** [comment]
For non-Lane e-resources records the Holdings locations will indicate the owning Library in terms of SUL, Law etc. See locations below. Does the current filter look at 856s also? 
Here are Law examples - https://folio-test.stanford.edu/inventory?filters=holdingsPermanentLocation.c6ce7052-e365-47d5-a98d-41daf68e7a1f&segment=holdings&sort=title 

BUS-ELECTRONIC
BUS-SDR
HILA-ELECTRONIC
HILA-SDR
LAW-ELECTRONIC
LAW-SDR
SUL-ELECTRONIC
SUL-SDR

Lane is more complex in their locations. They have many digital locations. @saseestone and I are meeting with them soon and could discuss then if needed. But here are just a couple of Lane examples 

https://folio-test.stanford.edu/inventory?filters=holdingsPermanentLocation.ce250ebb-807f-460a-9afa-b2087645e4a8%2CholdingsPermanentLocation.e0e30813-6c76-4876-8be0-fd9b2a90b7da&segment=holdings&sort=title

**Comment by corylown** [comment]
@ahafele is there a complete list of Lane electronic location codes somewhere? I think I'll need this in order to select the right holding to use for the owning library of the electronic resource. (Although, maybe we expect that any of the holdings on a record would have the right location...I'm not sure.)

**Comment by ahafele** [comment]
@corylown I will ask Lane for this.

**Comment by ahafele** [comment]
LANE-ECOLL
LANE-ECOMP
LANE-EDATA
LANE-EDOC
LANE-EPER
LANE-IMAGE

**Comment by corylown** [comment]
thank you @ahafele !
